# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: cudd
  version: "3.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/ivmai/cudd/archive/${{ name|lower }}-${{ version }}.tar.gz
    md5: edca9c69528256ca8ae37be9cedef73f
    sha256: 5fe145041c594689e6e7cf4cd623d5f2b7c36261708be8c9a72aed72cf67acce

build:
  skip: [win]
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - make
    - automake
    - libtool

tests:
  - package_contents:
      files:
        - lib/libcudd.a
      lib:
        - cudd
      include:
        - cudd.h

about:
  homepage: https://web.archive.org/web/20180127051756/http://vlsi.colorado.edu/~fabio/CUDD/html/index.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A package written in C for the manipulation of decision diagrams.
  description: |
    The CUDD package is a package written in C for the manipulation of decision
    diagrams.  It supports binary decision diagrams (BDDs), algebraic decision diagrams
    (ADDs), and Zero-Suppressed BDDs (ZDDs).
  repository: https://github.com/ivmai/cudd

extra:
  recipe-maintainers:
    - anand-bala
