# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
#
context:
  name: dd
  version: "0.6.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://files.pythonhosted.org/packages/18/b2/57a2d7151e7e904092e0411f79e8dadfc3ae143679236a9dec88f4667f8a/dd-0.6.0.tar.gz
    md5: f846f4f667381700f07488cbe0055da3
    sha256: 4baadadc9b2ebf6136a5b84dc51a43cec5fe91203286cd377e1e093358cdffcd
    target_directory: dd
    patches:
      - 0001-don-t-hardcode-gcc-as-the-compiler.patch
      - 0002-don-t-upperbound-ply-version.patch
  - url: https://github.com/ivmai/cudd/archive/cudd-3.0.0.tar.gz
    md5: edca9c69528256ca8ae37be9cedef73f
    sha256: 5fe145041c594689e6e7cf4cd623d5f2b7c36261708be8c9a72aed72cf67acce
    target_directory: dd/cudd-3.0.0

build:
  number: 0
  skip:
    - win
    - match(python, "<=3.10")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cython >=3.0.0
    - make
    - automake
    - libtool
  host:
    - python
    - pip
    - setuptools >=65.6.0
    - wheel
  run:
    - python
    - astutils >=0.0.5
    - networkx >=2.4
    - ply >=3.4

tests:
  - python:
      imports:
        - dd
        - dd.cudd
      pip_check: false

about:
  homepage: https://github.com/tulip-control/dd
  summary: Binary decision diagrams implemented in pure Python, as well as Cython wrappers of CUDD, Sylvan, and BuDDy.
  license: BSD-3-Clause
  license_file: dd/LICENSE

extra:
  recipe-maintainers:
    - anand-bala
