context: {}

package:
  name: astutils
  version: 0.0.6

source:
  - url: https://files.pythonhosted.org/packages/88/d9/86e4053d44baa2b648596a443e2bcf5b8e1d30a9669b14bfacc5307fbc2f/astutils-0.0.6.tar.gz
    sha256: e9a6f31b243ecfc3c7c84dd2f145cf5de83e475b650d2a6b781cfa713ad15427
    patches:
      - 0001-don-t-upperbound-ply-version.patch

build:
  number: 0
  skip:
    - match(python, "<=3.10")
  script: python -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - ply >=3.4

tests:
  - python:
      imports:
        - astutils
      pip_check: false

about:
  homepage: https://github.com/johnyf/astutils
  summary: Utilities for abstract syntax trees and parsing with PLY.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anand-bala
